server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

openai:
  api:
    key:
    url: https://api.openai.com/v1/chat/completions

